Update fp-verify.yml

diff --git a/.github/workflows/fp-verify.yml b/.github/workflows/fp-verify.yml
--- a/.github/workflows/fp-verify.yml
+++ b/.github/workflows/fp-verify.yml
@@ -1,124 +1,79 @@
-name: New-FP
-on:
-  pull_request:
-    types: [opened, synchronize]
-    paths:
-      - 'bbn-1/finality-providers/registry/**.json'
-      - 'bbn-1/finality-providers/sigs/**.sig'
+#!/bin/bash -eu
 
-jobs:
-  build-eotsd:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          repository: babylonchain/finality-provider
-          ref: v0.3.0
-      - name: Cache eotsd
-        id: cache-eots
-        uses: actions/cache@v4
-        with:
-          path: |
-            ./build/eotsd
-          key: key-eotsd-v030
-      - name: Setup go
-        uses: actions/setup-go@v5
-        with:
-          go-version: 1.21
-      - name: Compile
-        run: |
-          go mod download
-          make build
+# USAGE:
+# ./verify-new-fp.sh [nickname]
 
-  changed-fp-files:
-    runs-on: ubuntu-latest
-    outputs:
-      any_changed: ${{steps.changed-files-registry.outputs.any_changed}}
-      all_changed_files: ${{steps.changed-files-registry.outputs.all_changed_files}}
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Get changed files
-        id: changed-files-registry
-        uses: tj-actions/changed-files@v44
-        with:
-          files: 'bbn-1/finality-providers/registry/*.json'
+# checks if the finality provider located at bbn-1/finality-providers/registry/${nickname}.json has a
+# valid finality provider registration.
 
-  verify-new-fp:
-    needs:
-      - build-eotsd
-      - changed-fp-files
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - name: Load eotsd
-        id: cache-bin
-        uses: actions/cache@v4
-        with:
-          path: |
-            ./build/eotsd
-          key: key-eotsd-v030
-      - name: Debug Environment
-        run: |
-          echo "Current working directory:"
-          pwd
-          echo "List of files in current directory:"
-          ls -la
-          echo "Content of bbn-1/finality-providers/registry directory:"
-          ls -la bbn-1/finality-providers/registry
-          echo "Content of bbn-1/finality-providers/sigs directory:"
-          ls -la bbn-1/finality-providers/sigs
-          echo "EOTSD binary information:"
-          file ./build/eotsd
-          ./build/eotsd --help || echo "Failed to run eotsd --help"
-      - name: Debug EOTSD
-        run: |
-          echo "EOTSD binary location:"
-          ls -l ./build/eotsd
-          echo "EOTSD version (if available):"
-          ./build/eotsd version || echo "Version command not available"
-          echo "EOTSD help output:"
-          ./build/eotsd --help
+CWD="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
+regexEmail="^[a-z0-9!#\$%&'*+/=?^_\`{|}~-]+(\.[a-z0-9!#$%&'*+/=?^_\`{|}~-]+)*@([a-z0-9]([a-z0-9-]*[a-z0-9])?\.)+[a-z0-9]([a-z0-9-]*[a-z0-9])?\$"
 
-      - name: Debug Signature Verification
-        run: |
-          echo "Manual signature verification:"
-          ./build/eotsd verify-schnorr-sig \
-            --eots-pk 9b749016b734ce7de03712310cbb289b5d21db97af8e5227081acd5505af070c \
-            --signature-file bbn-1/finality-providers/sigs/blockpi.sig \
-            bbn-1/finality-providers/registry/blockpi.json
-            
-      - name: Verify new FPs
-        if: needs.changed-fp-files.outputs.any_changed == 'true'
-        env:
-          ALL_CHANGED_FILES: ${{ needs.changed-fp-files.outputs.all_changed_files }}
-        run: |
-          for filePathRegistryFP in ${ALL_CHANGED_FILES}; do
-            echo "Processing file: $filePathRegistryFP"
-            nickname=$(basename "$filePathRegistryFP" .json)
-            echo "Nickname: $nickname"
-            echo "Content of JSON file:"
-            cat "$filePathRegistryFP"
-            echo "Content of signature file:"
-            cat "bbn-1/finality-providers/sigs/${nickname}.sig"
-            echo "Running verification script:"
-            EOTSD_BIN=./build/eotsd ./bbn-1/finality-providers/scripts/verify-valid-fp.sh $nickname
-            echo "Verification script exit code: $?"
-          done
-      - name: Check verify-valid-fp.sh script
-        run: |
-          echo "Content of verify-valid-fp.sh script:"
-          cat ./bbn-1/finality-providers/scripts/verify-valid-fp.sh
-      - name: Debug EOTSD version
-        run: |
-          echo "EOTSD binary location:"
-          which ./build/eotsd
-          echo "EOTSD file information:"
-          file ./build/eotsd
-          echo "EOTSD version information (if available):"
-          ./build/eotsd --version || echo "No version flag available"
-          echo "EOTSD help information:"
-          ./build/eotsd --help
-          echo "Go build information:"
-          go version -m ./build/eotsd || echo "Unable to get Go build info"
+NICKNAME=${1:-""}
+EOTSD_BIN="${EOTSD_BIN:-eotsd}"
+
+if [ ${#NICKNAME} -lt 2 ]; then
+  echo $NICKNAME "should have more than 2 characters"
+  exit 1
+fi
+
+fpFilePath="$CWD/../registry/${NICKNAME}.json"
+if [ ! -f $fpFilePath ]; then
+  echo "$fpFilePath does not exist. Check whether you passed a valid finality provider nickname and stored the files in the correct locations."
+  exit 1
+fi
+
+signatureFilePath=$CWD/../sigs/$NICKNAME.sig
+if [ ! -f $signatureFilePath ]; then
+  echo "$signatureFilePath does not exist. Check whether you passed a valid finality provider nickname and stored the files in the correct locations."
+  exit 1
+fi
+
+if ! command -v jq &> /dev/null; then
+  echo "⚠️ jq command could not be found!"
+  echo "Install it by following the instructions here https://stedolan.github.io/jq/download/"
+  exit 1
+fi
+
+if ! command -v $EOTSD_BIN &> /dev/null; then
+  echo "⚠️ $EOTSD_BIN command could not be found!"
+  echo "Install it by following the instructions here https://github.com/babylonlabs-io/finality-provider/blob/v0.3.0"
+  exit 1
+fi
+
+echo "Verifying $fpFilePath"
+
+moniker=$(cat "$fpFilePath" | jq -r '.description.moniker')
+echo "Finality Provider Moniker: $moniker"
+if [ ${#moniker} -lt 3 ]; then
+  echo "$moniker has less than 3 characters"
+  exit 1
+fi
+
+securityContact=$(cat "$fpFilePath" | jq -r '.description.security_contact')
+echo "Finality Provider Security Contact: $securityContact"
+if [ ${#securityContact} -lt 4 ]; then
+  echo "$securityContact has less than 4 characters"
+  exit 1
+fi
+
+if ! [[ $securityContact =~ $regexEmail ]]; then
+  echo "$securityContact is not a valid email. Check whether you passed a valid finality provider email."
+fi
+
+commission=$(cat "$fpFilePath" | jq -r '.commission')
+echo "Finality Provider Commission: $commission"
+if ! [[ "$commission" =~ ^0\.[0-9]+$ ]]; then
+  echo "$commission is not valid commission decimal."
+  exit 1
+fi
+
+eots_pk=$(cat "$fpFilePath" | jq -r '.eots_pk')
+echo "Finality Provider EOTS Public Key: $eots_pk"
+
+signature=$(cat "$signatureFilePath" | xargs)
+echo "Finality Provider Signature: $signature"
+
+echo "Verifying signature with eotsd..."
+
+$EOTSD_BIN verify-schnorr-sig "$fpFilePath" --eots-pk $eots_pk --signature $signature
